{% set version = "2.0.8" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-performanceanalytics
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PerformanceAnalytics_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PerformanceAnalytics/PerformanceAnalytics_{{ version }}.tar.gz
  sha256: 64e209808038e1037f01a6f4e1f9d6a6a852c886765c619d2b5a66c583675ec3

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - r-xts                      # [build_platform != target_platform]
    - r-quadprog                 # [build_platform != target_platform]
    - r-zoo                      # [build_platform != target_platform]
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-quadprog
    - r-xts >=0.10.0
    - r-zoo
  run:
    - r-base
    - r-quadprog
    - r-xts >=0.10.0
    - r-zoo

test:
  commands:
    - $R -e "library('PerformanceAnalytics')"           # [not win]
    - "\"%R%\" -e \"library('PerformanceAnalytics')\""  # [win]

about:
  home: https://github.com/braverock/PerformanceAnalytics
  license: GPL-2.0-or-later
  summary: Collection of econometric functions for performance and risk  analysis. In addition to standard risk and performance metrics, this  package aims to aid practitioners and researchers in utilizing the latest research in analysis of non-normal return streams.  In general, it is most  tested on return (rather than
    price) data on a regular scale, but most  functions will work with irregular return data as well, and increasing numbers of functions will work with P&L or price data where possible.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: PerformanceAnalytics
# Type: Package
# Title: Econometric Tools for Performance and Risk Analysis
# Authors@R: c( person(given=c("Brian","G."),family="Peterson",role=c("cre","aut","cph"), email="brian@braverock.com") , person(given="Peter",family="Carl",role=c("aut","cph"), email="peter@braverock.com") , person(given="Kris",family="Boudt",role=c("ctb","cph")) , person(given="Ross",family="Bennett",role="ctb") , person(given="Joshua",family="Ulrich",role="ctb") , person(given="Eric",family="Zivot",role="ctb") , person(given="Dries",family="Cornilly",role="ctb") , person(given="Eric",family="Hung",role="ctb") , person(given="Matthieu",family="Lestel",role="ctb") , person(given="Kyle",family="Balkissoon",role="ctb")   , person(given="Diethelm",family="Wuertz",role="ctb")   )
# Version: 1.5.3
# Date: 2019-06-22 $Date$
# Description: Collection of econometric functions for performance and risk  analysis. In addition to standard risk and performance metrics, this  package aims to aid practitioners and researchers in utilizing the latest research in analysis of non-normal return streams.  In general, it is most  tested on return (rather than price) data on a regular scale, but most  functions will work with irregular return data as well, and increasing numbers of functions will work with P&L or price data where possible.
# Imports: methods, quadprog, zoo
# Depends: R (>= 3.0.0), xts (>= 0.10.0)
# Suggests: dygraphs, Hmisc, MASS, quantmod, gamlss, gamlss.dist, robustbase, quantreg, gplots, testthat
# License: GPL-2 | GPL-3
# Encoding: UTF-8
# URL: https://github.com/braverock/PerformanceAnalytics
# Copyright: (c) 2004-2019
# RoxygenNote: 6.1.1.9000
# NeedsCompilation: yes
# Packaged: 2019-06-22 21:24:37.467506 UTC; brian
# Author: Brian G. Peterson [cre, aut, cph], Peter Carl [aut, cph], Kris Boudt [ctb, cph], Ross Bennett [ctb], Joshua Ulrich [ctb], Eric Zivot [ctb], Dries Cornilly [ctb], Eric Hung [ctb], Matthieu Lestel [ctb], Kyle Balkissoon [ctb], Diethelm Wuertz [ctb]
# Maintainer: Brian G. Peterson <brian@braverock.com>
# Repository: CRAN
# Date/Publication: 2019-06-23 16:50:03 UTC
