travis:
  secure:
    BINSTAR_TOKEN: VhhI5zp5tbr/I0LgUz8T7+EagmhG95hzqtJR6VXRzkOSkf3cuwn23SYMYIRLmRrt08EP295f5kOBevBHaLzYOgZu9yo/y5qBUX29AHurfNupYTL0r4JvH9hrNVvocJt/Xi3FdzIS0cRh2EQWHguck9276tO8X3DwbYx++NHdNkhwHjsn1v1MKfZPem2L792izTBN/aQD0+nnDdyztCQWgl92C8SbLzGmz5csWM/nWvQQ9AOKoxlGgtrxR5FQym4acdY954PXIllfY9RYrplFGqMi9Kb1NkwNg8soFgJZo4oMFotqz7IHIad3JOYlIzfsCsOWsYjUkgcNPJhVcWkIAvHtpqxmloTgli4ymY2hEqd14CKiPFP2BHePODXIMzZTTIelgADpY7FC6UgTXPqb9A8wykVyDIVxD4Z3jUND64ZTnd8OEEXJM0e3O2dBAPDK/Ma7zCDUZm1+OKBt4bKUgimJ6CSnxz+pv128JZpzpX8b7skAOzuE7sVVM4zmEsBhWufja/JyFs/jK406ZXpI9L/r1rv17fnv2N+tdoIWE5hA7uYfzku0bnPPIceLiikbWdhcgD7Fk6+qXGpVAJfGuz7eBbljgSIRnzdqAtKkR8dA9CpMZTT20BvqUEjyeryvMS1URhDWMl73rNv/SmTUn0iHS12bfPvW/33VWRwuUew=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
